import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hy';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.courses': 'Courses',
    'nav.forBeginners': 'For Beginners',
    'nav.about': 'About',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.announcements': 'Announcements',
    'nav.getStarted': 'Get Started',
    
    'hero.title': 'Learn American Accounting',
    'hero.subtitle': 'Practical. Advanced. Remote-friendly.',
    'hero.description': 'Master Zoho Books and QuickBooks, practice on real US-style data, and start freelancing worldwide. Bonus 2-day English class included.',
    'hero.viewCourses': 'View Courses',
    'hero.contactUs': 'Contact Us',
    'hero.studentsTrained': '50+ students trained',
    
    'features.title': 'Practical American Accounting in Armenia',
    'features.description': 'PPA (Pen & Paper Accounting) trains accountants and beginners in American bookkeeping and accounting software. Our course emphasizes practical skills used by US contractors, small businesses, and freelancers.',
    'features.zoho': 'Zoho Books',
    'features.zohoDesc': 'US-oriented accounting workflows',
    'features.quickbooks': 'QuickBooks Online (QBO)',
    'features.quickbooksDesc': 'Industry-leading US platform',
    'features.practical': 'Practical practice',
    'features.practicalDesc': 'Work with real datasets and simulated companies',
    'features.freelance': 'Freelance guide',
    'features.freelanceDesc': 'Step-by-step to Upwork, Fiverr, and remote accounting work',
    'features.english': 'Bonus: 2-day English class',
    'features.englishDesc': 'Focused on accounting vocabulary',
    'features.seeCourseDetails': 'See Course Details',
    'features.scheduleConsultation': 'Schedule Consultation',
    'features.testimonial': 'I landed my first remote bookkeeping job after the PPA practical stage.',
    'features.testimonialAuthor': 'Anna K., PPA Graduate',
    'features.instagramTitle': 'Follow Our Journey',
    'features.instagramDesc': 'See what our students are achieving',
    'features.viewInstagram': 'View Instagram Feed',
    
    'footer.newsletter': 'Stay Updated',
    'footer.newsletterPlaceholder': 'Enter your email',
    'footer.subscribe': 'Subscribe',
    'footer.questions': 'Questions? Book a Free Consultation',
    'footer.questionsDesc': 'Get personalized advice about which course track is right for you',
    'footer.scheduleCall': 'Schedule Call',
    'footer.copyright': '© 2024 PPA - Pen & Paper Accounting. All rights reserved.',
    'footer.disclaimer': 'This site is informational. No payments through site.',
    'footer.privacy': 'Privacy Policy',
    
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.readMore': 'Read More',
    'common.viewAll': 'View All',
    'common.getStarted': 'Get Started',
    'common.contactUs': 'Contact Us',
    'common.learnMore': 'Learn More',
    'common.other': 'Other',
    
    'about.title': 'About PPA (Pen & Paper Accounting)',
    'about.mission': 'Our Mission',
    'about.team': 'Meet Our Team',
    'about.values': 'Our Values',
    'about.teamDescription': 'Our instructors bring real-world experience and industry expertise to every lesson.',
    'about.valuesDescription': 'These principles guide everything we do at PPA.',
    'about.expertise': 'Expertise:',
    'about.readyTitle': 'Ready to Start Your Journey?',
    'about.readyDescription': 'Join our community of successful accountants who are now working with US clients and building their freelance careers.',
    'about.readyPrimary': 'View Courses',
    'about.readySecondary': 'Get in Touch',
    'about.badge.practical': 'Practical Learning',
    'about.badge.global': 'Global Focus',
    'about.badge.studentSuccess': 'Student Success',
    'about.stats.students': 'Students Trained',
    'about.stats.placement': 'Job Placement Rate',
    'about.stats.experience': 'Years Experience',
    'about.stats.clients': 'US Clients Served',
    
    'courses.title': 'Courses — for Accountants & Beginners',
    'courses.description': 'Two tailored tracks designed for different experience levels. Both include four stages of practical training and a bonus English mini-course to prepare you for the American accounting market.',
    'courses.advanced': 'Advanced Track',
    'courses.beginner': 'Beginner Track',
    'courses.advancedDesc': 'For professional accountants who want to work with US businesses and clients',
    'courses.beginnerDesc': 'No prior experience required',
    'courses.viewSyllabus': 'View Syllabus',
    'courses.requestConsultation': 'Request Consultation',
    'courses.commonBenefitsTitle': "What's Included in Both Tracks",
    'courses.commonBenefitsDesc': 'Every student receives comprehensive support and resources',
    'courses.whatYoullLearn': "What You'll Learn",
    'courses.target': 'Target',
    'courses.duration': 'Duration',
    'courses.format': 'Format',
    'courses.readyCtaTitle': 'Ready to Begin Your Journey?',
    'courses.readyCtaDesc': 'Choose the track that matches your experience level and start building your American accounting career today.',
    'courses.viewFaq': 'View FAQ',
    'courses.meta.duration': '14-16 weeks',
    'courses.meta.groupSize': 'Small class sizes',
    'courses.meta.certificate': 'Certification included',
    'courses.benefit.certificateTitle': 'Certificate of Completion',
    'courses.benefit.certificateDesc': 'Official certification upon successful course completion',
    'courses.benefit.englishTitle': '2-Day English Class',
    'courses.benefit.englishDesc': 'Bonus accounting vocabulary and client communication',
    'courses.benefit.portfolioTitle': 'Portfolio Development',
    'courses.benefit.portfolioDesc': 'Build a professional portfolio with real project examples',
    'courses.benefit.freelanceTitle': 'Freelance Support',
    'courses.benefit.freelanceDesc': 'Help with Upwork/Fiverr profiles and client proposals',
    
    'faq.title': 'Frequently Asked Questions',
    'faq.description': 'Find answers to common questions about our courses, schedules, and requirements. Can\'t find what you\'re looking for? We\'re here to help!',
    'faq.needHelp': 'Need More Help?',
    'faq.readyToStart': 'Ready to Get Started?',
    'faq.generalCategory': 'General',
    'faq.searchPlaceholder': 'Search FAQs...',
    'faq.all': 'All',
    'faq.noResults': 'No FAQs found matching your search.',
    'faq.ctaFallbackDescription': 'Get in touch with our team and we will help you choose the right learning path.',
    
    'contact.title': 'Contact Us',
    'contact.description': 'Ready to start your American accounting journey? Get in touch to learn more about our courses and find the right track for your goals.',
    'contact.sendMessage': 'Send Us a Message',
    'contact.formDescription': 'Fill out the form below and we\'ll get back to you within 24 hours.',
    'contact.firstName': 'First Name',
    'contact.lastName': 'Last Name',
    'contact.email': 'Email',
    'contact.phone': 'Phone (Optional)',
    'contact.course': 'Interested Course',
    'contact.startDate': 'Preferred Start Date',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell us about your background, goals, and any questions you have...',
    'contact.sendButton': 'Send Message',
    'contact.requiredNote': '* Required fields. We\'ll never share your information with third parties.',
    'contact.getInTouch': 'Get in Touch',
    'contact.officeHours': 'Office Hours',
    'contact.quickHelp': 'Need Quick Help?',
    'contact.scheduleCall': 'Schedule Free Call',
    'contact.haveQuestions': 'Have Questions?',
    'contact.faqFallback': 'Check out our frequently asked questions for quick answers about courses, schedules, and requirements.',
    'contact.label.email': 'Email',
    'contact.label.phone': 'Phone',
    'contact.label.location': 'Location',
    'contact.label.instagram': 'Instagram',
    'contact.label.linkedin': 'LinkedIn',
    'contact.label.facebook': 'Facebook',
    
    'days.monday': 'Monday',
    'days.tuesday': 'Tuesday',
    'days.wednesday': 'Wednesday',
    'days.thursday': 'Thursday',
    'days.friday': 'Friday',
    'days.saturday': 'Saturday',
    'days.sunday': 'Sunday',

    'ann.title': 'Announcements',
    'ann.searchPlaceholder': 'Search announcements...',
    'ann.filter.all': 'All',
    'ann.filter.category': 'Filter by category',
    'ann.sort.label': 'Sort',
    'ann.sort.newest': 'Newest',
    'ann.sort.oldest': 'Oldest',
    'ann.loadMore': 'Load more',
    'ann.category': 'Category (Optional)',
    'ann.noResults': 'No announcements found',
    'ann.readMore': 'Read more',
    'ann.backToList': 'Back to announcements',
    'ann.relatedTo': 'Related to',
    'ann.addNew': 'Add Announcement',
    'ann.edit': 'Edit Announcement',
    'ann.delete': 'Delete Announcement',
    'ann.titleLabel': 'Title',
    'ann.summaryLabel': 'Summary',
    'ann.contentLabel': 'Content',
    'ann.categoryLabel': 'Category',
    'ann.category.courses': 'All Courses',
    'ann.category.jobs': 'Job Announcements',
    'ann.category.news': 'News',
    'ann.imageLabel': 'Image URL (optional)',
    'ann.imagesLabel': 'Gallery Images',
    'ann.pinned': 'Pin to top',
    'ann.share': 'Copy link',
    'ann.relatedCourseLabel': 'Related Course (optional)',
    'ann.relatedAnnouncements': 'Related Announcements',
    'ann.save': 'Save',
    'ann.cancel': 'Cancel',
  },
  hy: {
    'nav.home': 'Գլխավոր',
    'nav.courses': 'Դասընթացներ',
    'nav.forBeginners': 'Սկսնակների համար',
    'nav.about': 'Մեր մասին',
    'nav.faq': 'Հաճախակի հարցեր',
    'nav.contact': 'Կապ',
    'nav.announcements': 'Հայտարարություններ',
    'nav.getStarted': 'Սկսել',
    
    'hero.title': 'Սովորեք ամերիկյան հաշվապահություն',
    'hero.subtitle': 'Գործնական. Առաջադեմ. Հեռավոր.',
    'hero.description': 'Տիրապետեք Zoho Books-ին և QuickBooks-ին, աշխատեք իրական ամերիկյան տվյալների հետ և սկսեք ֆրիլանս աշխատանք աշխարհում: Բոնուս 2-օրյա անգլերեն դասընթաց:',
    'hero.viewCourses': 'Դիտել դասընթացները',
    'hero.contactUs': 'Կապ մեզ հետ',
    
    'features.title': 'Գործնական ամերիկյան հաշվապահություն Հայաստանում',
    'features.description': 'PPA (Pen & Paper Accounting) պատրաստում է հաշվապահներ և սկսնակներ ամերիկյան հաշվապահական համակարգերի համար: Մեր դասընթացը ընդգծում է գործնական հմտությունները, որոնք օգտագործվում են ամերիկյան կապալառուների, փոքր բիզնեսների և ֆրիլանսերների կողմից:',
    'features.zoho': 'Zoho Books',
    'features.zohoDesc': 'Ամերիկյան հաշվապահական աշխատանքներ',
    'features.quickbooks': 'QuickBooks Online (QBO)',
    'features.quickbooksDesc': 'Առաջատար ամերիկյան հարթակ',
    'features.practical': 'Գործնական պրակտիկա',
    'features.practicalDesc': 'Աշխատեք իրական տվյալների և սիմուլացված ընկերությունների հետ',
    'features.freelance': 'Ֆրիլանս ուղեցույց',
    'features.freelanceDesc': 'Քայլ առ քայլ Upwork, Fiverr և հեռավոր հաշվապահական աշխատանք',
    'features.english': 'Բոնուս: 2-օրյա անգլերեն դասընթաց',
    'features.englishDesc': 'Հաշվապահական բառապաշարի վրա կենտրոնացած',
    'features.seeCourseDetails': 'Դիտել դասընթացի մանրամասները',
    'features.scheduleConsultation': 'Հանդիպում գրանցել',
    'features.testimonial': 'Ես ստացա իմ առաջին հեռավոր հաշվապահական աշխատանքը PPA գործնական փուլից հետո:',
    'features.testimonialAuthor': 'Աննա Կ., PPA շրջանավարտ',
    'features.instagramTitle': 'Հետևեք մեր ճանապարհին',
    'features.instagramDesc': 'Տեսեք, թե ինչ են հասնում մեր ուսանողները',
    'features.viewInstagram': 'Դիտել Instagram-ը',
    
    'footer.newsletter': 'Մնացեք թարմացված',
    'footer.newsletterPlaceholder': 'Մուտքագրեք ձեր էլ. փոստը',
    'footer.subscribe': 'Բաժանորդագրվել',
    'footer.questions': 'Հարցեր ունեք? Պահեք անվճար խորհրդատվություն',
    'footer.questionsDesc': 'Ստացեք անհատական խորհուրդ, թե որ դասընթացը ձեզ համար է:',
    'footer.scheduleCall': 'Հանդիպում գրանցել',
    'footer.copyright': '© 2024 PPA - Pen & Paper Accounting. Բոլոր իրավունքները պաշտպանված են:',
    'footer.disclaimer': 'Այս կայքը տեղեկատվական է: Կայքի միջոցով վճարումներ չեն կատարվում:',
    'footer.privacy': 'Գաղտնիության քաղաքականություն',
    
    'common.loading': 'Բեռնվում է...',
    'common.error': 'Սխալ',
    'common.success': 'Հաջողություն',
    'common.cancel': 'Չեղարկել',
    'common.save': 'Պահպանել',
    'common.edit': 'Խմբագրել',
    'common.delete': 'Ջնջել',
    'common.close': 'Փակել',
    'common.back': 'Վերադառնալ',
    'common.next': 'Հաջորդ',
    'common.previous': 'Նախորդ',
    'common.submit': 'Ուղարկել',
    'common.readMore': 'Կարդալ ավելին',
    'common.viewAll': 'Դիտել բոլորը',
    'common.getStarted': 'Սկսել',
    'common.contactUs': 'Կապ մեզ հետ',
    'common.learnMore': 'Իմանալ ավելին',
    'common.other': 'Այլ',
    
    'about.title': 'PPA-ի մասին (Pen & Paper Accounting)',
    'about.mission': 'Մեր առաքելությունը',
    'about.team': 'Հանդիպեք մեր թիմին',
    'about.values': 'Մեր արժեքները',
    'about.teamDescription': 'Մեր դասախոսները յուրաքանչյուր դասի բերում են իրական աշխատանքային փորձ և ոլորտային գիտելիք։',
    'about.valuesDescription': 'Այս սկզբունքներն են առաջնորդում PPA-ում մեր ամենօրյա աշխատանքը։',
    'about.expertise': 'Մասնագիտացում',
    'about.readyTitle': 'Պատրա՞ստ եք սկսել ձեր ճանապարհը',
    'about.readyDescription': 'Միացեք մեր շրջանավարտների համայնքին, ովքեր արդեն աշխատում են ԱՄՆ հաճախորդների հետ և զարգացնում հեռավար կարիերա։',
    'about.readyPrimary': 'Դիտել դասընթացները',
    'about.readySecondary': 'Կապ մեզ հետ',
    'about.badge.practical': 'Գործնական ուսուցում',
    'about.badge.global': 'Գլոբալ ուղղվածություն',
    'about.badge.studentSuccess': 'Ուսանողի հաջողություն',
    'about.stats.students': 'Ուսանողներ պատրաստված',
    'about.stats.placement': 'Աշխատանքի տեղադրման տոկոս',
    'about.stats.experience': 'Տարիների փորձ',
    'about.stats.clients': 'Ամերիկյան հաճախորդներ',
    
    'courses.title': 'Դասընթացներ — հաշվապահների և սկսնակների համար',
    'courses.description': 'Երկու հարմարեցված ուղի տարբեր փորձի մակարդակների համար: Երկուսն էլ ներառում են գործնական ուսուցման չորս փուլ և բոնուս անգլերեն մինի-դասընթաց ամերիկյան հաշվապահական շուկայի համար պատրաստվելու համար:',
    'courses.advanced': 'Ընդլայնված ուղի',
    'courses.beginner': 'Սկսնակների ուղի',
    'courses.advancedDesc': 'Պրոֆեսիոնալ հաշվապահների համար, ովքեր ցանկանում են աշխատել ամերիկյան բիզնեսների և հաճախորդների հետ',
    'courses.beginnerDesc': 'Նախնական փորձ չի պահանջվում',
    'courses.viewSyllabus': 'Դիտել ուսումնական պլանը',
    'courses.requestConsultation': 'Պահանջել խորհրդատվություն',
    'courses.commonBenefitsTitle': 'Ի՞նչ է ներառված երկու ուղիներում',
    'courses.commonBenefitsDesc': 'Յուրաքանչյուր ուսանող ստանում է համապարփակ աջակցություն և ռեսուրսներ',
    'courses.whatYoullLearn': 'Կսովորեք',
    'courses.target': 'Նպատակային',
    'courses.duration': 'Տևողություն',
    'courses.format': 'Ձևաչափ',
    'courses.readyCtaTitle': 'Պատրա՞ստ եք սկսել ձեր ճանապարհը',
    'courses.readyCtaDesc': 'Ընտրեք ձեր փորձին համապատասխան ուղին և սկսեք կառուցել ձեր ամերիկյան հաշվապահական կարիերան այսօր։',
    'courses.viewFaq': 'Դիտել ՀՃՀ',
    'courses.meta.duration': '14-16 շաբաթ',
    'courses.meta.groupSize': 'Փոքր խմբեր',
    'courses.meta.certificate': 'Սերտիֆիկատ ներառված է',
    'courses.benefit.certificateTitle': 'Ավարտական սերտիֆիկատ',
    'courses.benefit.certificateDesc': 'Պաշտոնական սերտիֆիկացում դասընթացի հաջող ավարտից հետո',
    'courses.benefit.englishTitle': '2-օրյա անգլերեն դաս',
    'courses.benefit.englishDesc': 'Հաշվապահական բառապաշար և հաճախորդի հետ հաղորդակցման պրակտիկա',
    'courses.benefit.portfolioTitle': 'Պորտֆոլիոյի կառուցում',
    'courses.benefit.portfolioDesc': 'Կառուցեք պրոֆեսիոնալ պորտֆոլիո իրական նախագծային օրինակներով',
    'courses.benefit.freelanceTitle': 'Ֆրիլանս աջակցություն',
    'courses.benefit.freelanceDesc': 'Օգնություն Upwork/Fiverr պրոֆիլների և առաջարկների պատրաստման մեջ',
    
    'faq.title': 'Հաճախակի հարցեր',
    'faq.description': 'Գտեք պատասխաններ մեր դասընթացների, ժամանակացույցի և պահանջների մասին հաճախակի հարցերին: Չե՞ք կարող գտնել այն, ինչ փնտրում եք: Մենք այստեղ ենք օգնելու:',
    'faq.needHelp': 'Կարիք ունե՞ք ավելի շատ օգնության:',
    'faq.readyToStart': 'Պատրա՞ստ եք սկսել:',
    'faq.generalCategory': 'Ընդհանուր',
    'faq.searchPlaceholder': 'Փնտրել հարցերը...',
    'faq.all': 'Բոլորը',
    'faq.noResults': 'Ձեր որոնմանը համապատասխան հարցեր չեն գտնվել։',
    'faq.ctaFallbackDescription': 'Կապվեք մեր թիմի հետ, և մենք կօգնենք ընտրել ձեր նպատակներին համապատասխան ուսուցման ուղին։',
    
    'contact.title': 'Կապ մեզ հետ',
    'contact.description': 'Պատրա՞ստ եք սկսել ձեր ամերիկյան հաշվապահական ճանապարհը: Կապվեք մեզ հետ ավելի շատ իմանալու համար մեր դասընթացների մասին և գտնել ձեզ համար ճիշտ ուղին:',
    'contact.sendMessage': 'Ուղարկեք մեզ հաղորդագրություն',
    'contact.formDescription': 'Լրացրեք ստորև բերված ձևը, և մենք կպատասխանենք 24 ժամվա ընթացքում:',
    'contact.firstName': 'Անուն',
    'contact.lastName': 'Ազգանուն',
    'contact.email': 'Էլ. փոստ',
    'contact.phone': 'Հեռախոս (ըստ ցանկության)',
    'contact.course': 'Հետաքրքրող դասընթաց',
    'contact.startDate': 'Նախընտրելի մեկնարկի ամսաթիվ',
    'contact.message': 'Հաղորդագրություն',
    'contact.messagePlaceholder': 'Գրեք ձեր փորձի, նպատակների և հարցերի մասին...',
    'contact.sendButton': 'Ուղարկել հաղորդագրություն',
    'contact.requiredNote': '* Պարտադիր դաշտեր։ Մենք երբեք չենք փոխանցի ձեր տվյալները երրորդ կողմին։',
    'contact.getInTouch': 'Կապվեք մեզ հետ',
    'contact.officeHours': 'Աշխատանքային ժամեր',
    'contact.quickHelp': 'Արագ օգնության կարիք ունե՞ք:',
    'contact.scheduleCall': 'Ամրագրել անվճար զանգ',
    'contact.haveQuestions': 'Հարցե՞ր ունեք',
    'contact.faqFallback': 'Տեսեք հաճախակի տրվող հարցերը՝ դասընթացների, ժամանակացույցի և պահանջների վերաբերյալ արագ պատասխաններ ստանալու համար։',
    'contact.label.email': 'Էլ. փոստ',
    'contact.label.phone': 'Հեռախոս',
    'contact.label.location': 'Հասցե',
    'contact.label.instagram': 'Instagram',
    'contact.label.linkedin': 'LinkedIn',
    'contact.label.facebook': 'Facebook',
    
    'days.monday': 'Երկուշաբթի',
    'days.tuesday': 'Երեքշաբթի',
    'days.wednesday': 'Չորեքշաբթի',
    'days.thursday': 'Հինգշաբթի',
    'days.friday': 'Ուրբաթ',
    'days.saturday': 'Շաբաթ',
    'days.sunday': 'Կիրակի',

    'ann.title': 'Հայտարարություններ',
    'ann.searchPlaceholder': 'Փնտրել հայտարարությունների մեջ...',
    'ann.filter.all': 'Բոլորը',
    'ann.filter.category': 'Ֆիլտր ըստ կատեգորիայի',
    'ann.sort.label': 'Դասավորել',
    'ann.sort.newest': 'Նորերը',
    'ann.sort.oldest': 'Հիները',
    'ann.loadMore': 'Բեռնել ավելին',
    'ann.category': 'Կատեգորիա (ըստ ցանկության)',
    'ann.noResults': 'Հայտարարություններ չեն գտնվել',
    'ann.readMore': 'Կարդալ ավելին',
    'ann.backToList': 'Վերադառնալ հայտարարություններին',
    'ann.relatedTo': 'Կապված է',
    'ann.addNew': 'Ավելացնել հայտարարություն',
    'ann.edit': 'Խմբագրել հայտարարությունը',
    'ann.delete': 'Ջնջել հայտարարությունը',
    'ann.titleLabel': 'Վերնագիր',
    'ann.summaryLabel': 'Կարճ նկարագրություն',
    'ann.contentLabel': 'Բովանդակություն',
    'ann.categoryLabel': 'Կատեգորիա',
    'ann.category.courses': 'Առկա բոլոր դասընթացները',
    'ann.category.jobs': 'Աշխատանքի հայտարարություններ',
    'ann.category.news': 'Նորություններ',
    'ann.imageLabel': 'Նկար (վերնագիր)',
    'ann.imagesLabel': 'Պատկերասրահ',
    'ann.pinned': 'Ամրացնել վերևում',
    'ann.share': 'Պատճենել հղումը',
    'ann.relatedCourseLabel': 'Կապված դասընթաց (ըստ ցանկության)',
    'ann.relatedAnnouncements': 'Կապված հայտարարություններ',
    'ann.save': 'Պահպանել',
    'ann.cancel': 'Չեղարկել',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('ppa-language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'hy')) {
      setLanguage(savedLanguage);
    } else {
      const browserLanguage = (navigator.language || '').toLowerCase();
      const timezone = (Intl.DateTimeFormat().resolvedOptions().timeZone || '').toLowerCase();
      const isArmenian = browserLanguage.startsWith('hy') || timezone.includes('yerevan');
      setLanguage(isArmenian ? 'hy' : 'en');
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('ppa-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
